spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Demo?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8081